routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/

Auth::routes();

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');

    Route::resource('users', 'UsersController');
    Route::resource('users-api', 'UsersApiController');
    Route::resource('profile', 'ProfileController');
});

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/

Route::post('oauth/access_token', function () {
    return Response::json(Authorizer::issueAccessToken());
});

Route::get('api/get-ready/{id}', 'ApiService@getReady');
Route::post('api/login', 'ApiService@login');

/*
|--------------------------------------------------------------------------
| Custom API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "oauth" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'oauth'], function () {
    Route::post('api/passwords', 'PasswordService@passwords');
});

resources/views/get-ready.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <section class="blur-container">
            <div class="blur"></div>
            <div class="panel panel-default">
                <div class="panel-heading">Set a password</div>
                <div class="panel-body">
                    {{-- Form --}}
                    <form action="{{ route('profile.update', $id) }}" method="post">
                        {{ method_field('PUT') }}

                        <input type="hidden" name="tab" value="password">

                        {{-- Password --}}
                        <div class="form-group {{ $errors->has('password') ? ' has-error has-feedback' : '' }}">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password"
                                   placeholder="Password" required>

                            @if ($errors->has('password'))
                                @include('components.error', ['errors' => $errors->get('password')])
                            @endif
                        </div>
                        {{-- End Password --}}

                        {{-- Confirm Password --}}
                        <div class="form-group {{ $errors->has('confirm-password') ? ' has-error has-feedback' : '' }}">
                            <label for="confirmPassword">Confirm Password</label>
                            <input type="password" class="form-control" id="confirmPassword"
                                   name="confirm_password" placeholder="Confirm Password" required>

                            @if ($errors->has('confirm-password'))
                                @include('components.error', ['errors' => $errors->get('confirm-password')])
                            @endif
                        </div>
                        {{-- End Confirm Password --}}

                        {{-- Actions --}}
                        <section id="actions" class="pull-right">
                            <button type="submit" class="btn btn-primary">Setup</button>
                        </section>
                        {{-- End Actions --}}
                    </form>
                    {{-- End Form --}}
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.api')

@section('css')
    <link href="{{ asset('/public/plugins/dataTables/jquery.dataTables.css') }}" rel="stylesheet">
@endsection

@section('content')
    {{-- Routes --}}
    <section id="tableView">
        {{-- Header --}}
        <div class="header">
            <h2 class="page-header title">Routes</h2>
        </div>
        {{-- End Header --}}

        {{-- Table Routes --}}
        <div class="table-responsive">
            <table class="table table-striped" id="tableRoutes">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Route</th>
                    <th>Method</th>
                    <th>Controller</th>
                    <th>Action</th>
                    <th>Middleware (Route)</th>
                    <th>Middleware (Controller)</th>
                </tr>
                </thead>
                <tbody>
                @foreach($routes as $route)
                    <tr>
                        <td>#</td>
                        <td>{{ $route->route }}</td>
                        <td>{{ $route->method }}</td>
                        <td>{{ $route->controller }}</td>
                        <td>{{ $route->action }}</td>
                        <td>{{ $route->middleware }}</td>
                        <td>{{ $route->controllerMiddleware }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{-- End Table Routes --}}
    </section>
    {{-- End Routes --}}
@endsection

@section('js')
    <script src="{{ asset('/public/plugins/dataTables/jquery.dataTables.js') }}"></script>

    <script>
        var tableId = 'tableRoutes';

        $(document).ready(function () {
            // Init dataTable
            $('#tableRoutes').DataTable();
        });
    </script>

    <script src="{{ asset('/public/js/table-view.js') }}"></script>
@endsection

resources/views/profile.blade.php
@extends('layouts.api')

@section('content')
    <section id="profilePage">
        <h1 class="page-header title">Profile</h1>

        <div class="row">
            <div class="col-md-12">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation"
                        class="{{ old('tab') === 'profile' ? 'active' : (old('tab') === null ? 'active' : '') }}">
                        <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a>
                    </li>

                    <li role="presentation" class="@if (old('tab') === 'password') active @endif">
                        <a href="#password" aria-controls="password" role="tab" data-toggle="tab">Change Password</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    {{-- Profile --}}
                    <div role="tabpanel"
                         class="tab-pane {{ old('tab') === 'profile' ? 'active' : (old('tab') === null ? 'active' : '') }}"
                         id="profile">
                        {{-- Form --}}
                        <form action="{{ route('profile.update', base64_encode($user->id)) }}" method="post">
                            {{ method_field('PUT') }}

                            <input type="hidden" name="tab" value="profile">

                            {{-- Name --}}
                            <div class="form-group {{ $errors->has('name') ? ' has-error has-feedback' : '' }}">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name"
                                       value="{{ old('name') ?: $user->name }}" required>

                                @if ($errors->has('name'))
                                    @include('components.error', ['errors' => $errors->get('name')])
                                @endif
                            </div>
                            {{-- End Name --}}

                            {{-- Actions --}}
                            <section id="actions" class="pull-right">
                                <button type="button" class="btn btn-default"
                                        onclick="window.location='{{ url('/') }}'">Cancel
                                </button>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </section>
                            {{-- End Actions --}}
                        </form>
                        {{-- End Form --}}
                    </div>
                    {{-- End Profile --}}

                    {{-- Change Password --}}
                    <div role="tabpanel" class="tab-pane @if (old('tab') === 'password') active @endif" id="password">
                        {{-- Form --}}
                        <form action="{{ route('profile.update', base64_encode($user->id)) }}" method="post">
                            {{ method_field('PUT') }}

                            <input type="hidden" name="tab" value="password">

                            {{-- Password --}}
                            <div class="form-group {{ $errors->has('password') ? ' has-error has-feedback' : '' }}">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password"
                                       placeholder="Password" required>

                                @if ($errors->has('password'))
                                    @include('components.error', ['errors' => $errors->get('password')])
                                @endif
                            </div>
                            {{-- End Password --}}

                            {{-- Confirm Password --}}
                            <div class="form-group {{ $errors->has('confirm-password') ? ' has-error has-feedback' : '' }}">
                                <label for="confirmPassword">Confirm Password</label>
                                <input type="password" class="form-control" id="confirmPassword"
                                       name="confirm_password" placeholder="Confirm Password" required>

                                @if ($errors->has('confirm-password'))
                                    @include('components.error', ['errors' => $errors->get('confirm-password')])
                                @endif
                            </div>
                            {{-- End Confirm Password --}}

                            {{-- Actions --}}
                            <section id="actions" class="pull-right">
                                <button type="button" class="btn btn-default"
                                        onclick="window.location='{{ url('/') }}'">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </section>
                            {{-- End Actions --}}
                        </form>
                        {{-- End Form --}}
                    </div>
                    {{-- End Change Password --}}
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/users-api.blade.php
@extends('layouts.api')

@section('css')
    <link href="{{ asset('/public/plugins/dataTables/jquery.dataTables.css') }}" rel="stylesheet">
@endsection

@section('content')
    <section id="tableView">
        <div class="header">
            <h2 class="page-header title">Users API</h2>

            {{-- Actions --}}
            <div id="actions" class="pull-right">
                <button type="button" class="btn btn-new" data-toggle="modal" data-target="#userApiModal">
                    New
                </button>
            </div>
            {{-- End Actions --}}
        </div>

        <div class="table-responsive">
            {{-- Users API Table --}}
            <table class="table table-striped" id="tableUsersApi">
                {{-- Header --}}
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                {{-- End Header --}}

                {{-- Body --}}
                <tbody>
                @foreach($usersApi as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ explode(' ', $user->created_at)[0] }}</td>
                        {{-- Actions --}}
                        <td>
                            {{-- Edit --}}
                            <img src="{{ url('public/images/icons/icon_edit.svg') }}" title="Edit User" id="editUser{{ $user->id }}"
                                 user-id="{{ $user->id }}">
                            {{-- End Edit --}}

                            {{-- Delete --}}
                            <img src="{{ url('public/images/icons/icon_delete.svg') }}" title="Delete User"
                                 id="deleteUser{{ $user->id }}" user-id="{{ $user->id }}"
                                 data-toggle="modal" data-target="#deleteModal" data-id="{{ $user->id }}"
                                 data-name="{{ $user->name }}">
                            {{-- End Delete --}}
                        </td>
                        {{-- Actions --}}
                    </tr>
                @endforeach
                </tbody>
                {{-- End Body --}}
            </table>
            {{-- End Users API Table --}}
        </div>
    </section>

    <section id="parentUserModal">
        @include('components.datatable.new-user-api')
    </section>

    <section id="parentDeleteModal">
        @include('components.datatable.delete-user')
    </section>
@endsection

@section('js')
    <script src="{{ asset('/public/plugins/dataTables/jquery.dataTables.js') }}"></script>

    <script>
        var tableId = 'tableUsersApi';
        var $dataTableId = '#tableUsersApi';
        var $modalTitle = 'Edit User API';
        var $modalUrl = '/users-api/';
        var $deleteMessage = 'user api';
        var $old = false;
        var $newUser = $('#parentUserModal').html();
        var $modalId = '#userApiModal';

        function editModal() {
        }
    </script>

    @include('components.js.datatable-view')
    <script src="{{ asset('/public/js/table-view.js') }}"></script>
@endsection

resources/views/users.blade.php
@extends('layouts.api')

@section('css')
    <link href="{{ asset('/public/plugins/dataTables/jquery.dataTables.css') }}" rel="stylesheet">
@endsection

@section('content')
    <section id="tableView">
        <div class="header">
            <h2 class="page-header title">Users</h2>

            {{-- Actions --}}
            <div id="actions" class="pull-right">
                <button type="button" class="btn btn-new" data-toggle="modal" data-target="#userModal">
                    New
                </button>
            </div>
            {{-- End Actions --}}
        </div>

        <div class="table-responsive">
            {{-- Users Table --}}
            <table class="table table-striped" id="tableUsers">
                {{-- Header --}}
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                {{-- End Header --}}

                {{-- Body --}}
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ explode(' ', $user->created_at)[0] }}</td>
                        {{-- Actions --}}
                        <td>
                            {{-- Edit --}}
                            <img src="{{ url('public/images/icons/icon_edit.svg') }}" title="Edit User"
                                 id="editUser{{ $user->id }}"
                                 user-id="{{ $user->id }}">
                            {{-- End Edit --}}

                            {{-- Delete --}}
                            <img src="{{ url('public/images/icons/icon_delete.svg') }}" title="Delete User"
                                 id="deleteUser{{ $user->id }}" user-id="{{ $user->id }}"
                                 data-toggle="modal" data-target="#deleteModal" data-id="{{ $user->id }}"
                                 data-name="{{ $user->name }}">
                            {{-- End Delete --}}
                        </td>
                        {{-- Actions --}}
                    </tr>
                @endforeach
                </tbody>
                {{-- End Body --}}
            </table>
            {{-- End Users Table --}}
        </div>
    </section>

    <section id="parentUserModal">
        @include('components.datatable.new-user')
    </section>

    <section id="parentDeleteModal">
        @include('components.datatable.delete-user')
    </section>
@endsection

@section('js')
    <script src="{{ asset('/public/plugins/dataTables/jquery.dataTables.js') }}"></script>

    <script>
        var tableId = 'tableUsers';
        var $dataTableId = '#tableUsers';
        var $modalTitle = 'Edit User';
        var $modalUrl = '/users/';
        var $deleteMessage = 'user';
        var $old = false;
        var $newUser = $('#parentUserModal').html();
        var $modalId = '#userModal';

        function editModal() {
            // Remove attribute required from password input
            $($modalId + ' #password').removeAttr('required');
        }
    </script>

    @include('components.js.datatable-view')
    <script src="{{ asset('/public/js/table-view.js') }}"></script>
@endsection